[package]
name = "capstone"
version = "0.1.0"
authors = ["Ole A. Sjo Fasting <oasf@polygo.no>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "master" }
# num-traits = "0.2"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
